import { IPO, Sector } from './types';

export const SECTORS: Sector[] = [
  'Hydropower',
  'Microfinance',
  'Insurance',
  'Development Bank',
  'Commercial Bank',
  'Manufacturing',
  'Hotels & Tourism',
  'Investment',
  'Others'
];

export const BASE_RATES: Record<Sector, number> = {
  'Hydropower': 70,
  'Microfinance': 45,
  'Insurance': 55,
  'Development Bank': 50,
  'Commercial Bank': 40,
  'Manufacturing': 60,
  'Hotels & Tourism': 65,
  'Investment': 50,
  'Others': 50
};

export const TRANSLATIONS = {
  EN: {
    home: 'Home',
    predictor: 'Predictor',
    history: 'IPO History',
    education: 'Education',
    about: 'About',
    admin: 'Admin',
    heroTitle: 'Will You Get the IPO? Find Out Before the Result.',
    heroSub: 'Nepal\'s smartest IPO allotment probability at one click.',
    checkChances: 'Check My Allotment Chances',
    howItWorks: 'How It Works',
    step1: 'Enter IPO Details',
    step2: 'Our Algorithm Analyzes Data',
    step3: 'Get Your Probability Score',
    recentResults: 'Recent IPO Results',
    testimonials: 'What Investors Say',
    selectIPO: 'Select the IPO',
    appDetails: 'Application Details',
    predict: 'Predict My Allotment',
    analyzing: 'Our algorithm is analyzing 500+ historical IPOs...',
    verdictLow: 'Low Chance',
    verdictMod: 'Moderate Chance',
    verdictGood: 'Good Chance',
    verdictHigh: 'Very High Chance',
    expectedKitta: 'Expected Kitta You May Receive',
    shareFB: 'Share on Facebook',
    tips: 'Apply Tips',
    searchPlaceholder: 'Search by company name...',
    mission: 'Our Mission',
    contactUs: 'Contact Us',
    disclaimer: 'Disclaimer: This tool provides probability estimates based on historical patterns. It is not financial advice.',
    predictorTitle: 'IPO Allotment Predictor',
    predictorSub: 'Enter details below to calculate your statistical probability of allotment.',
    selectCompany: 'Select the Company',
    predictNow: 'Predict Now'
  },
  NP: {
    home: 'होम',
    predictor: 'प्रेडिक्टर',
    history: 'IPO इतिहास',
    education: 'शिक्षा',
    about: 'हाम्रो बारेमा',
    admin: 'एडमिन',
    heroTitle: 'के तपाईलाई IPO पर्ला? नतिजा अगावै थाहा पाउनुहोस्।',
    heroSub: 'नेपालको सबै IPO को बाँडफाँड सम्भावना एक क्लिकमा।',
    checkChances: 'मेरो सम्भावना जाँच गर्नुहोस्',
    howItWorks: 'यसले कसरी काम गर्छ',
    step1: 'IPO विवरणहरू भर्नुहोस्',
    step2: 'हाम्रो एल्गोरिदमले डेटा विश्लेषण गर्दछ',
    step3: 'तपाईको सम्भाव्यता स्कोर प्राप्त गर्नुहोस्',
    recentResults: 'भर्खरका IPO नतिजाहरू',
    testimonials: 'लगानीकर्ताहरू के भन्छन्',
    selectIPO: 'IPO छान्नुहोस्',
    appDetails: 'आवेदन विवरणहरू',
    predict: 'मेरो बाँडफाँड भविष्यवाणी गर्नुहोस्',
    analyzing: 'हाम्रो एल्गोरिदमले ५००+ ऐतिहासिक IPO हरू विश्लेषण गर्दैछ...',
    verdictLow: 'कम सम्भावना',
    verdictMod: 'मध्यम सम्भावना',
    verdictGood: 'राम्रो सम्भावना',
    verdictHigh: 'धेरै उच्च सम्भावना',
    expectedKitta: 'तपाईले प्राप्त गर्न सक्ने अपेक्षित कित्ता',
    shareFB: 'फेसबुकमा सेयर गर्नुहोस्',
    tips: 'आवेदन सुझावहरू',
    searchPlaceholder: 'कम्पनीको नाम खोज्नुहोस्...',
    mission: 'हाम्रो लक्ष्य',
    contactUs: 'हामीलाई सम्पर्क गर्नुहोस',
    disclaimer: 'अस्वीकरण: यो उपकरणले ऐतिहासिक ढाँचाहरूमा आधारित सम्भाव्यता अनुमानहरू प्रदान गर्दछ। यो वित्तीय सल्लाह होइन।',
    predictorTitle: 'IPO बाँडफाँड प्रेडिक्टर',
    predictorSub: 'बाँडफाँडको सम्भावना गणना गर्न तलको विवरणहरू भर्नुहोस्।',
    selectCompany: 'कम्पनी छान्नुहोस्',
    predictNow: 'भविष्यवाणी गर्नुहोस्'
  }
};
